In [1]:
#create 10x10 array with random values, find minimum and maximum
import numpy as np
a = np.random.random((10,10))
print(a)
amin, amax = a.min(), a.max()
print("Minimum and Maximum values:")
print(amin, amax)


[[0.0952988  0.58582004 0.39344952 0.90126408 0.55197914 0.48127185
  0.17476971 0.38630591 0.77103558 0.01194708]
 [0.95737702 0.22154147 0.44308334 0.80463614 0.44938483 0.4388972
  0.22195823 0.35554957 0.37674971 0.17109919]
 [0.7779416  0.3746229  0.84200743 0.81829961 0.02947133 0.6107557
  0.49295536 0.98016689 0.25316336 0.11643458]
 [0.69862877 0.98786588 0.72553954 0.68335769 0.9496779  0.58849552
  0.76369378 0.50562319 0.33661364 0.47645915]
 [0.65008598 0.08513739 0.7512825  0.15161002 0.39629442 0.61262823
  0.99316058 0.54649638 0.17331559 0.29813438]
 [0.05845096 0.39895353 0.39096934 0.16646972 0.19205203 0.97751755
  0.24126695 0.77196125 0.90118767 0.44033088]
 [0.83870145 0.14482243 0.17489245 0.77760322 0.56597034 0.04430739
  0.18532206 0.72632099 0.60125343 0.87175704]
 [0.24242268 0.46335928 0.87977429 0.52294245 0.95023562 0.60790353
  0.84108861 0.90688159 0.76391299 0.91224482]
 [0.16605618 0.47730896 0.93414716 0.0293343  0.71995268 0.53676384
  0.81265654 0

In [2]:
# create a 2nd array with 1 on borfder and zero inside
import numpy as np
a = np.ones((10,10))
print(a)
print("1 in the border and 0 in the array")
a[1:-1,1:-1]= 0
print(a)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
1 in the border and 0 in the array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
