In [1]:
# How to swap two array in a row
import numpy as np
a = np.array([[1,2,3],[8,9,4],[5,6,7],[3,5,6]])
print(a)
print("swapping of rows")
b = a[[0,2]] = a[[2,0]] 
print(b)

[[1 2 3]
 [8 9 4]
 [5 6 7]
 [3 5 6]]
swapping of rows
[[5 6 7]
 [1 2 3]]


In [2]:
# Compute averages over an array
import numpy as np
a = np.array([[1,2,3],[4,5,6,],[7,8,9]])
print(a)
print("finding averages of arrays")
avg = np.average(a,axis=0)
print(avg)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
finding averages of arrays
[4. 5. 6.]
