In [1]:
# How to swap two array in a row
import numpy as np
a = np.array([[1,2,3],[8,9,4],[5,6,7],[3,5,6]])
print(a)
print("swapping of rows")
b = a[[0,2]] = a[[2,0]] 
print(b)

[[1 2 3]
 [8 9 4]
 [5 6 7]
 [3 5 6]]
swapping of rows
[[5 6 7]
 [1 2 3]]


In [5]:
# Compute averages over an array
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.cumsum(a)/ np.size(a)
print(b)



[0.11111111 0.33333333 0.66666667 1.11111111 1.66666667 2.33333333
 3.11111111 4.         5.        ]
